---
  appKey: "anoima-svr"
  appName:
    ja: "あの人は今？"
  version: 0.1.0
  webappbase: "/"
  defaultLang: ja
  session:
    secret: "jiotsrfjkh54r89ysrgehuigruihregui"
    resave: false
    saveUninitialized: false
    cookie:
  sequelize:
    global:
      database: "database"
      username: null
      password: null
      options:
        dialect: "mysql"
        replication:
          write:
            host: "127.0.0.1"
            port: 3306
            database: "anoima_global"
            username: "anoima_usr"
            password: "anoima001"
          read:
            - host: "127.0.0.1"
              port: 3306
              database: "anoima_global"
              username: "anoima_usr_r"
              password: "anoima002"
        pool:
          maxConnections: 10
          maxIdleTime: 300
    shardable:
      - database: "database"
        username: null
        password: null
        options:
          dialect: "mysql"
          replication:
            write:
              host: "127.0.0.1"
              port: 3306
              database: "anoima_shardable1"
              username: "anoima_usr"
              password: "anoima001"
            read:
              - host: "127.0.0.1"
                port: 3306
                database: "anoima_shardable1"
                username: "anoima_usr_r"
                password: "anoima002"
          pool:
            maxConnections: 10
            maxIdleTime: 300
      - database: "database"
        username: null
        password: null
        options:
          dialect: "mysql"
          replication:
            write:
              host: "127.0.0.1"
              port: 3306
              database: "anoima_shardable2"
              username: "anoima_usr"
              password: "anoima001"
            read:
              - host: "127.0.0.1"
                port: 3306
                database: "anoima_shardable2"
                username: "anoima_usr_r"
                password: "anoima002"
          pool:
            maxConnections: 10
            maxIdleTime: 300
  password:
    algorithm: "sha256"
  superAccount:
    mailAddress: 'admin'
    password: 'admin01'
    role: 'super'
  passport:
    facebook:
      clientID: "PLEASE_SET_YOUR_APP_ID"
      clientSecret: "PLEASE_SET_YOUR_APP_SECRET"
      callbackURL: "http://YOUR_DOMAIN.example/auth/facebook/callback"
  log4js:
    appenders:
      - type: "datefile"
        category: "access" # アクセスログ
        filename: "/var/log/local/anoima/access.log"
        pattern: "-yyyy-MM-dd"
        backups: 10
      - type: "datefile"
        category: "http" # 通信ログ
        filename: "/var/log/local/anoima/http.log"
        pattern: "-yyyy-MM-dd"
        backups: 10
      - type: "datefile"
        category: "error" # エラーログ
        filename: "/var/log/local/anoima/error.log"
        pattern: "-yyyy-MM-dd"
        maxLogSize: 107374182400 # 100MB
      - type: "file"
        category: "debug" # デバッグログ
        filename: "/var/log/local/anoima/debug.log"
        backups: 10
        maxLogSize: 10737418240 # 10MB
      - type: "console" # コンソール
    levels:
      access: "INFO"
      http: "INFO"
      error: "INFO"
      debug: "DEBUG"
    replaceConsole: true
  noaccesslog:
    - \.css
    - \.js
    - \.png
    - \.jpg
    - \.gif
    - \.ico
  swagger:
    swagger: "2.0"
    info:
      title: "あの人は今？"
      version: 0.1.0
      description: "あの人は今？WebアプリのサーバーサイドAPI。"
    basePath: "/api"
    consumes:
      - "application/json"
    produces:
      - "application/json"
      - "text/plain"
    definitions:
      Person:
        type: object
        description: あの人情報
        required:
          - id
          - ownerId
          - name
          - privacy
        properties:
          id:
            type: integer
            format: int32
            description: あの人ID
          ownerId:
            type: integer
            format: int32
            description: 所有者ID
          name:
            type: string
            description: あの人の名前
          privacy:
            type: string
            description: 公開設定
          text:
            type: string
            description: あの人の説明
          createdAt:
            type: string
            format: date-time
            description: 登録日時
          updatedAt:
            type: string
            format: date-time
            description: 更新日時
      PersonMap:
        type: object
        description: あの人ID-キーマッピング
        required:
          - id
          - key
          - no
        properties:
          id:
            type: integer
            format: int32
            description: あの人ID
          key:
            type: string
            description: あの人キー
          no:
            type: integer
            format: int32
            description: DB番号
          createdAt:
            type: string
            format: date-time
            description: 登録日時
          updatedAt:
            type: string
            format: date-time
            description: 更新日時
      PersonWithMap:
        allOf:
          - $ref: '#/definitions/Person'
          - properties:
              map:
                $ref: '#/definitions/PersonMap'
      User:
        type: object
        description: ユーザー情報
        required:
          - id
        properties:
          id:
            type: integer
            format: int32
            description: ユーザーID
          note:
            type: string
            description: ノート
          createdAt:
            type: string
            format: date-time
            description: 登録日時
          updatedAt:
            type: string
            format: date-time
            description: 更新日時
      Bookmark:
        type: object
        description: ブックマーク
        required:
          - id
        properties:
          id:
            type: integer
            format: int32
            description: ブックマークID
          userId:
            type: integer
            format: int32
            description: ユーザーID
          personId:
            type: integer
            format: int32
            description: あの人ID
          createdAt:
            type: string
            format: date-time
            description: 作成日時
      BookmarkWithPerson:
        allOf:
          - $ref: '#/definitions/Bookmark'
          - properties:
              person:
                $ref: '#/definitions/PersonWithMap'
    parameters:
      personKey:
        in: path
        name: key
        description: あの人キー
        type: string
      offset:
        in: query
        name: offset
        description: 開始位置
        type: integer
        format: int32
      limit:
        in: query
        name: limit
        description: 取得件数
        type: integer
        format: int32
    responses:
      BadRequest:
        description: バリデーションNG
        schema:
          type: string
      Unauthorized:
        description: 認証NG
        schema:
          type: string
      Forbidden:
        description: 権限NG
        schema:
          type: string
      NotFound:
        description: 該当データ無し
        schema:
          type: string
    securityDefinitions:
      UserSessionId:
        type: apiKey
        in: header
        name: Cookie
        description: ユーザーセッションID
      AdminSessionId:
        type: apiKey
        in: header
        name: Cookie
        description: 管理者セッションID
