---
  sequelize:
    global:
      database: "anoima_global"
      username: ""
      password: ""
      options:
        dialect: "sqlite"
        storage: '/tmp/anoima_global_test.db'
    shardable:
      - database: "anoima_shardable1"
        username: ""
        password: ""
        options:
          dialect: "sqlite"
          storage: '/tmp/anoima_shardable1_test.db'
      - database: "anoima_shardable2"
        username: ""
        password: ""
        options:
          dialect: "sqlite"
          storage: '/tmp/anoima_shardable2_test.db'
  log4js:
    appenders:
      - type: "console"
        category: "access" # アクセスログ
      - type: "console"
        category: "http" # 通信ログ
      - type: "console"
        category: "error" # エラーログ
      - type: "console"
        category: "debug" # デバッグログ
      - type: "console" # コンソール
    levels:
      access: "INFO"
      http: "INFO"
      error: "INFO"
      debug: "INFO"
    replaceConsole: false
